name = "tgbot-biliantitracking"

main = "./index.js"
compatibility_date = "2023-03-21"
workers_dev = true

vars = { TG_BOT_TOKEN = "0123456789:AaBbCcDdEeFfGgHhIiJjKk-AaBbCcDdEeFf" }

[env.dev]
vars = { TG_BOT_TOKEN = "0123456789:AaBbCcDdEeFfGgHhIiJjKk-AaBbCcDdEeFf" }
