name = "tgbot-biliantitracking"

main = "./index.js"
compatibility_date = "2021-09-28"
workers_dev = true

vars = { TG_WEBHOOK_URL = "https://tgbot-biliantitracking.yjbeetle.workers.dev", TG_BOT_TOKEN = "" }

[env.dev]
vars = { TG_WEBHOOK_URL = "https://xxx.xxx", TG_BOT_TOKEN = "" }
